# 1. RDSへの接続設定
# 接続するDBを指定。
spring.datasource.url=jdbc:mysql://pbl-group-2.c74c442iwj4m.us-east-1.rds.amazonaws.com:3306/pbl_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
# RDSに接続するときのユーザ名
spring.datasource.username=admin
# RDSに接続するときのパスワード
spring.datasource.password=pbl-root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. JPA/Hibernateの設定（Javaの変更に合わせてテーブルを自動調整する設定）
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# 3. メール送信の設定(下記6行)
# メール送信に使用するGmailのSMTPサーバーを指定する。
spring.mail.host=smtp.gmail.com
# メール送信に使用するGmailのポート番号を指定する。
spring.mail.port=587
# メール送信に使用するGmailのアカウントを指定する。
spring.mail.username=25110036@oic-ok.ac.jp
# メール送信に使用するGmailのパスワードを指定する。
spring.mail.password=jiqo xcgr ogus symy
# メール送信に使用するGmailのSMTPサーバーの認証を有効にする。
spring.mail.properties.mail.smtp.auth=true
# メール送信に使用するGmailのSMTPサーバーのSTARTTLSを有効にする。
spring.mail.properties.mail.smtp.starttls.enable=true